import type { Metadata } from 'next';
import './globals.css';
import MainHeader from '@/common/header/MainHeader';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="font-pretendard relative flex min-h-screen w-full flex-col bg-white">
        <MainHeader />
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
