import type { Metadata } from "next";
import "./globals.css";
import { MainHeader } from "@/common/MainHeader";
import UpButton from "@/common/UpButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="min-h-full flex flex-col">
        <MainHeader />
        {children}
        <UpButton />
      </body>
    </html>
  );
}
