import type { Metadata } from 'next';
import './globals.css';
import Header from '@/common/header/Header';

export const metadata: Metadata = {
  title: '건축사무소 몸',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="font-pretendard min-h-screen w-full bg-white">
        <Header />
        <main className="min-h-0 flex-1 scroll-smooth lg:h-screen lg:snap-y lg:snap-mandatory lg:overflow-hidden lg:overflow-y-scroll">
          {children}
        </main>
      </body>
    </html>
  );
}
